# Generated by Django 5.1.2 on 2025-08-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ_SINGLE', 'MCQ Single Correct'), ('MCQ_MULTI', 'MCQ Multiple Correct'), ('NUMERICAL', 'Numerical Value')], default='MCQ_SINGLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='marks_obtained',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_marks',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
